import React, { Component } from 'react';
import './style.scss';
import Calendar from './Components/Calendar/Calendar';
class App extends Component {
  constructor() {
    super();
    let tripData = [
      {
        date: '2018/12/28',
        data: [{
          id: '1',
          no: '18TE806GJ1-T',
          name: '北北基一日遊',
          price: 1999,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/28',
          date_tripEnd: '2018/12/28',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: false,
          isAvailable: true
        },
        {
          id: '2',
          no: '18TE806GJ1-T',
          name: '北北基跨年遊',
          price: 2999,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/28',
          date_tripEnd: '2018/12/29',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: false,
          isAvailable: true
        },
        {
          id: '3',
          no: '18TE806GJ1-T',
          name: '北台灣Hi遊',
          price: 3600,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/28',
          date_tripEnd: '2018/12/30',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: false,
          isAvailable: true
        },
        {
          id: '4',
          no: '18TE806GJ1-T',
          name: '跨年Happy遊',
          price: 4999,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/28',
          date_tripEnd: '2018/12/31',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: false,
          isAvailable: true
        },
        {
          id: '5',
          no: '18TE806GJ1-T',
          name: '跨年北迴五日遊',
          price: 5999,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/28',
          date_tripEnd: '2019/01/01',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: false,
          isAvailable: true
        },
        {
          id: '6',
          no: '18TE806GJ1-T',
          name: '台灣一周遊',
          price: 6999,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/28',
          date_tripEnd: '2019/01/02',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: false,
          isAvailable: true
        },
        {
          id: '7',
          no: '18TE806GJ1-T',
          name: '北台一日遊',
          price: 7999,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/28',
          date_tripEnd: '2019/01/03',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: false,
          isAvailable: true
        }
        ]
      },
      {
        date: '2018/12/29',
        data: [{
          id: '1',
          no: '18TE806GJ1-T',
          name: '北北基一日遊',
          price: 199,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/29',
          date_tripEnd: '2018/12/29',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '2',
          no: '18TE806GJ1-T',
          name: '北北基跨年遊',
          price: 299,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/29',
          date_tripEnd: '2018/12/31',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: true
        },
        {
          id: '3',
          no: '18TE806GJ1-T',
          name: '北台灣Hi遊',
          price: 360,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/29',
          date_tripEnd: '2018/12/30',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: false,
          isAvailable: true
        },
        {
          id: '4',
          no: '18TE806GJ1-T',
          name: '跨年Happy遊',
          price: 499,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/29',
          date_tripEnd: '2018/12/31',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: false,
          isTheCheapest: true,
          isAvailable: true
        },
        {
          id: '5',
          no: '18TE806GJ1-T',
          name: '跨年北迴五日遊',
          price: 599,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/29',
          date_tripEnd: '2019/01/01',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: false,
          isTheCheapest: false,
          isAvailable: true
        },
        {
          id: '6',
          no: '18TE806GJ1-T',
          name: '台灣一周遊',
          price: 699,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/29',
          date_tripEnd: '2019/01/02',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: false,
          isAvailable: true
        },
        {
          id: '7',
          no: '18TE806GJ1-T',
          name: '北台一日遊',
          price: 799,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/29',
          date_tripEnd: '2019/01/03',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: false,
          isAvailable: true
        }
        ]
      },
      {
        date: '2018/12/30',
        data: [{
          id: '1',
          no: '18TE806GJ1-T',
          name: '北北基一日遊',
          price: 199,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/29',
          date_tripEnd: '2018/12/29',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '2',
          no: '18TE806GJ1-T',
          name: '北北基跨年遊',
          price: 299,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/30',
          date_tripEnd: '2018/12/31',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '3',
          no: '18TE806GJ1-T',
          name: '北台灣Hi遊',
          price: 360,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/30',
          date_tripEnd: '2018/12/30',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: true
        },
        {
          id: '4',
          no: '18TE806GJ1-T',
          name: '跨年Happy遊',
          price: 499,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/30',
          date_tripEnd: '2018/12/31',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '5',
          no: '18TE806GJ1-T',
          name: '跨年北迴五日遊',
          price: 599,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/30',
          date_tripEnd: '2019/01/01',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: true
        },
        {
          id: '6',
          no: '18TE806GJ1-T',
          name: '台灣一周遊',
          price: 699,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/30',
          date_tripEnd: '2019/01/02',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: false,
          isAvailable: true
        },
        {
          id: '7',
          no: '18TE806GJ1-T',
          name: '北台一日遊',
          price: 799,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/29',
          date_tripEnd: '2019/01/03',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: false,
          isAvailable: true
        }
        ]
      },
      {
        date: '2018/12/31',
        data: [{
          id: '1',
          no: '18TE806GJ1-T',
          name: '北北基一日遊',
          price: 199,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/29',
          date_tripEnd: '2018/12/29',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '2',
          no: '18TE806GJ1-T',
          name: '北北基跨年遊',
          price: 299,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/30',
          date_tripEnd: '2018/12/31',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '3',
          no: '18TE806GJ1-T',
          name: '北台灣Hi遊',
          price: 360,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/30',
          date_tripEnd: '2018/12/30',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '4',
          no: '18TE806GJ1-T',
          name: '跨年Happy遊',
          price: 499,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/30',
          date_tripEnd: '2018/12/31',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '5',
          no: '18TE806GJ1-T',
          name: '跨年北迴五日遊',
          price: 599,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/30',
          date_tripEnd: '2019/01/01',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '6',
          no: '18TE806GJ1-T',
          name: '台灣一周遊',
          price: 699,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/30',
          date_tripEnd: '2019/01/02',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '7',
          no: '18TE806GJ1-T',
          name: '北台一日遊',
          price: 799,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/29',
          date_tripEnd: '2019/01/03',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        }
        ]
      },
      {
        date: '2019/01/01',
        data: [{
          id: '1',
          no: '18TE806GJ1-T',
          name: '北北基一日遊',
          price: 199,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/29',
          date_tripEnd: '2018/12/29',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '2',
          no: '18TE806GJ1-T',
          name: '北北基跨年遊',
          price: 299,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/30',
          date_tripEnd: '2018/12/31',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '3',
          no: '18TE806GJ1-T',
          name: '北台灣Hi遊',
          price: 360,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/30',
          date_tripEnd: '2018/12/30',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '4',
          no: '18TE806GJ1-T',
          name: '跨年Happy遊',
          price: 499,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/30',
          date_tripEnd: '2018/12/31',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '5',
          no: '18TE806GJ1-T',
          name: '跨年北迴五日遊',
          price: 599,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/12/30',
          date_tripEnd: '2019/01/01',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '6',
          no: '18TE806GJ1-T',
          name: '台灣一周遊',
          price: 699,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2019/01/02',
          date_tripEnd: '2019/01/03',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: true
        },
        {
          id: '7',
          no: '18TE806GJ1-T',
          name: '北台一日遊',
          price: 799,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/01/01',
          date_tripEnd: '2019/01/03',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: true
        }
        ]
      },
      {
        date: '2019/01/02',
        data: [{
          id: '1',
          no: '18TE806GJ1-T',
          name: '北北基一日遊',
          price: 199,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2019/01/02',
          date_tripEnd: '2018/12/29',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '2',
          no: '18TE806GJ1-T',
          name: '北北基跨年遊',
          price: 299,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2019/01/02',
          date_tripEnd: '2018/12/31',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '3',
          no: '18TE806GJ1-T',
          name: '北台灣Hi遊',
          price: 360,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2019/01/02',
          date_tripEnd: '2018/12/30',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '4',
          no: '18TE806GJ1-T',
          name: '跨年Happy遊',
          price: 499,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2019/01/02',
          date_tripEnd: '2018/12/31',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '5',
          no: '18TE806GJ1-T',
          name: '跨年北迴五日遊',
          price: 599,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2019/01/02',
          date_tripEnd: '2019/01/01',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '6',
          no: '18TE806GJ1-T',
          name: '台灣一周遊',
          price: 699,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2019/01/02',
          date_tripEnd: '2019/01/03',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: true
        },
        {
          id: '7',
          no: '18TE806GJ1-T',
          name: '北台一日遊',
          price: 799,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/01/02',
          date_tripEnd: '2019/01/03',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: true
        }
        ]
      },
      {
        date: '2019/01/03',
        data: [{
          id: '1',
          no: '18TE806GJ1-T',
          name: '北北基一日遊',
          price: 199,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2019/01/03',
          date_tripEnd: '2018/12/29',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '2',
          no: '18TE806GJ1-T',
          name: '北北基跨年遊',
          price: 299,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2019/01/03',
          date_tripEnd: '2018/12/31',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '3',
          no: '18TE806GJ1-T',
          name: '北台灣Hi遊',
          price: 360,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2019/01/03',
          date_tripEnd: '2018/12/30',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '4',
          no: '18TE806GJ1-T',
          name: '跨年Happy遊',
          price: 499,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2019/01/03',
          date_tripEnd: '2019/01/03',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: true
        },
        {
          id: '5',
          no: '18TE806GJ1-T',
          name: '跨年北迴五日遊',
          price: 599,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2019/01/03',
          date_tripEnd: '2019/01/03',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: true
        },
        {
          id: '6',
          no: '18TE806GJ1-T',
          name: '台灣一周遊',
          price: 699,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2019/01/03',
          date_tripEnd: '2019/01/03',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: false
        },
        {
          id: '7',
          no: '18TE806GJ1-T',
          name: '北台一日遊',
          price: 799,
          seat_release: 87,
          seat_vacancy: 1,
          date_release: '2018/07/19',
          date_tripStart: '2018/01/03',
          date_tripEnd: '2019/01/03',
          flight_from: '高雄小港機場',
          flight_to: '台北松山機場',
          depart_from: '台灣高雄',
          arrive_at: '台灣台北',
          isGuaranteed: true,
          isTheCheapest: true,
          isAvailable: true
        }
        ]
      }
    ];
    let calendarData = {
      tableProps: {
        dateRange: {
          from: '2018/12/28',
          to: '2019/01/03'
        },
        speed: .3,   //M-每次移動所花費時間
        count: {
          slide: 1,  //M-每次前後移動行數
          show: 3    //M-畫面呈現行數
        }
      },
      tripData: tripData
    }


    this.state = {
      calendarData: calendarData,
      property:{
      count: {
        // M版時每次點擊往前往後移動幾格儲存格
        slide: 1, // [number] 
        // M版時一個畫面show幾格儲存格
        show: 3 // [number] 
      },
      // 設定花多久時間移動完成
      speed: .3, // [number] 
      }
    }
  }

  render() {
    return (
      <Calendar cldr={this.state.calendarData} property={this.state.property} />
    )
  }
}

export default App;
